# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Darren Hill Consulting Inc.
author:
  name: Darren Hill
  email: "darren@darrenhillconsulting.ca"

description: >- # this means to ignore newlines until "baseurl:"
  Explore our website to discover how we can elevate your business with expert NetSuite consulting services. Whether you're seeking assistance with ERP implementation, financial management, CRM optimization, or e-commerce solutions, Darren Hill Consulting Inc. is your trusted partner for unlocking the power of NetSuite.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://darrenhillconsulting.ca" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-sitemap

remote_theme: jekyll/minima

minima:
  skin: solarized
  social_links:
    - { platform: github,  user_url: "https://github.com/darrenhillconsulting" }
    - { platform: twitter, user_url: "https://twitter.com/dhillconsulting" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/darrenthill/" }
    - { platform: stackoverflow, user_url: "https://stackoverflow.com/users/5389329/darren-hill" }

google_analytics: GT-WK2RRBX8

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
